dist: xenial
sudo: false

language: python
python: 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python -m conan_inquiry find
  - python -m conan_inquiry generate
  - python -m conan_inquiry deploy 
